/**
 * Build a prompt for generating a micro-lesson about a concept.
 * The actual LLM generation will be done by the cron agent at delivery time.
 * 
 * @param concept - The concept to explain
 * @param paperTitle - Title of the paper where the concept appeared
 * @param paperAbstract - Abstract of the paper
 * @returns A prompt string to send to an LLM
 */
export function buildLessonPrompt(concept: string, paperTitle: string, paperAbstract: string): string {
  return `You are helping Mikey learn about LLM engineering concepts. Generate a concise micro-lesson (3-4 short paragraphs) explaining the following concept:

**Concept:** ${concept}

**Context:** This concept appeared in a recent arXiv paper:
- Title: ${paperTitle}
- Abstract: ${paperAbstract}

**Guidelines:**
- Start with a clear, practical definition (not overly academic)
- Explain why it matters in the context of LLM engineering
- Include a concrete example or analogy
- Keep it conversational and engaging
- Assume the reader has basic LLM knowledge but hasn't heard of this specific term
- If relevant, briefly mention how it relates to the paper context

**Format:** Plain text, 3-4 paragraphs, no headers or markdown formatting.`;
}

/**
 * Format a lesson response from the LLM.
 * Adds emoji, paper reference, and next steps.
 * 
 * @param concept - The concept being explained
 * @param lessonText - The lesson text generated by the LLM
 * @param paperTitle - Optional paper title for reference
 * @param arxivId - Optional arXiv ID
 * @returns Formatted lesson ready for delivery
 */
export function formatLesson(
  concept: string,
  lessonText: string,
  paperTitle?: string,
  arxivId?: string
): string {
  const lines: string[] = [];

  lines.push(`🎯 **${concept}**`);
  lines.push('');
  lines.push(lessonText);
  lines.push('');

  if (paperTitle) {
    lines.push(`📚 Seen in: ${paperTitle}${arxivId ? ` (arXiv:${arxivId})` : ''}`);
    lines.push('');
  }

  lines.push('💡 Reply "/gaps" to see all tracked concepts');

  return lines.join('\n');
}
